export type Level = "beginner" | "intermediate" | "advanced";
export type Category = "DRUMS" | "SOUND DESIGN" | "ARRANGEMENT" | "DJ STYLES" | "MIXING" | "PLUGINS" | "FUNDAMENTALS";

export interface AbletonParams {
  pitch?: string;
  filter?: string;
  sidechain?: string;
  eq?: string;
  tempo?: string;
  reverb?: string;
  delay?: string;
  [key: string]: string | undefined;
}

export interface Technique {
  id: string;
  title: string;
  category: Category;
  subgenre: string;
  level: Level;
  bpm?: string;
  time?: string;
  description?: string;
  steps?: string[];
  abletonParams?: AbletonParams;
  isPro?: boolean;
  relatedIds?: string[];
}

export const techniques: Technique[] = [
  // ── DRUMS ─────────────────────────────────────────────────────────
  {
    id: "dark-techno-kick",
    title: "Dark Techno Kick",
    category: "DRUMS",
    subgenre: "Dark Techno",
    level: "intermediate",
    bpm: "130–138",
    time: "15 min",
    description: "El kick oscuro que define el sonido de Tresor y Berghain.",
    steps: [
      "Carga 909 Core Kit en Ableton Drum Rack.",
      "Transpón el kick a -11 semitonos para bajar el pitch.",
      "Ajusta filtro Analog (OSR) con cutoff bajo para más oscuridad.",
      "Añade segunda capa de kick con más ataque y release largo — este crea el rumble.",
      "Sidechain ambos kicks al bus master con ratio 4:1, attack 1ms, release auto.",
      "Compresión paralela: mezcla 30% wet para mantener transientes.",
      "EQ: corta en 200–400 Hz para limpiar la mud, boost sutil en 60 Hz.",
    ],
    abletonParams: {
      pitch: "-11st",
      filter: "OSR Analog",
      sidechain: "ratio 4:1, attack 1ms",
      eq: "cut 200–400 Hz, boost 60 Hz",
    },
    relatedIds: ["industrial-kick", "hard-techno-kick"],
  },
  {
    id: "industrial-kick",
    title: "Industrial Kick",
    category: "DRUMS",
    subgenre: "Industrial Techno",
    level: "advanced",
    bpm: "140–150",
    time: "20 min",
    description: "Brutal, seco y distorsionado. El kick que aplasta salas.",
    steps: [
      "Sample de kick muy corto y seco, sin reverb.",
      "Saturación extrema con Overdrive — drive al 80%.",
      "Distorsión con Pedal amp para añadir grit.",
      "Transient shaper: ataque al máximo, sustain al mínimo.",
      "EQ: boost agresivo en 80 Hz, corta todo por encima de 8 kHz.",
      "Sin sidechain — el kick debe dominar brutalmente.",
    ],
    abletonParams: {
      overdrive: "drive 80%",
      transient: "attack max, sustain min",
      eq: "boost 80 Hz, cut >8 kHz",
    },
    relatedIds: ["dark-techno-kick", "hard-techno-kick"],
  },
  {
    id: "dub-techno-kick",
    title: "Dub Techno Kick",
    category: "DRUMS",
    subgenre: "Dub Techno",
    level: "beginner",
    bpm: "120–128",
    time: "12 min",
    description: "Minimalismo y espacio infinito. El corazón del dub techno.",
    steps: [
      "Kick limpio y simple — 909 sin procesar.",
      "Manda el kick a 3 returns: Return A con delay largo, Return B con reverb grande, Return C con resonator.",
      "Return A: delay 1/4 sincronizado, feedback 40%, filtro HPF en 200 Hz.",
      "Return B: reverb grande, decay 4s, HPF en 300 Hz para no ensuciar.",
      "Return C: resonator afinado a la tonalidad del track.",
      "El sonido viene de los returns, no del kick directo.",
      "Resultado: kick minimalista pero espacio infinito.",
    ],
    abletonParams: {
      delay: "1/4 sync, feedback 40%, HPF 200 Hz",
      reverb: "decay 4s, HPF 300 Hz",
      resonator: "tuned to track key",
    },
    relatedIds: ["minimal-kick", "melodic-techno-kick"],
  },
  {
    id: "melodic-techno-kick",
    title: "Melodic Techno Kick",
    category: "DRUMS",
    subgenre: "Melodic Techno",
    level: "beginner",
    bpm: "128–135",
    time: "10 min",
    description: "Suave pero contundente. El kick que convive con melodías.",
    steps: [
      "909 o sample suave — evita kicks muy distorsionados.",
      "Sub prominente: boost en 50–60 Hz, corta en 150–300 Hz.",
      "Sidechain suave: ratio 2:1, attack 5ms, release lento 200ms.",
      "Reverb muy corta (room) para dar espacio sin perder punch.",
      "Complementa con bassline que deje espacio al kick en el low-end.",
    ],
    abletonParams: {
      eq: "boost 50–60 Hz, cut 150–300 Hz",
      sidechain: "ratio 2:1, attack 5ms, release 200ms",
      reverb: "room, very short",
    },
    relatedIds: ["dub-techno-kick", "dub-chord"],
  },
  {
    id: "hard-techno-kick",
    title: "Hard Techno Kick",
    category: "DRUMS",
    subgenre: "Hard Techno",
    level: "intermediate",
    bpm: "145–160",
    time: "18 min",
    description: "Rápido, distorsionado y sin piedad. Construido para el caos.",
    steps: [
      "Kick muy corto: decay mínimo, sin cola.",
      "Pitch muy bajo: -14 a -16 semitonos.",
      "Distorsión extrema: Saturator en clip mode + Overdrive en cadena.",
      "Compresión brick wall: ratio 10:1, ataque 0ms.",
      "EQ: boost brutal en 60 Hz, corta completamente por encima de 5 kHz.",
      "Volumen alto — en hard techno el kick aplasta todo.",
    ],
    abletonParams: {
      pitch: "-14 to -16st",
      saturator: "clip mode",
      compression: "ratio 10:1, attack 0ms",
      eq: "boost 60 Hz, cut >5 kHz",
    },
    relatedIds: ["industrial-kick", "dark-techno-kick"],
  },
  {
    id: "minimal-kick",
    title: "Minimal Kick",
    category: "DRUMS",
    subgenre: "Minimal Techno",
    level: "beginner",
    bpm: "128–132",
    time: "8 min",
    description: "El groove viene del timing. Nada más, nada menos.",
    steps: [
      "909 limpio — casi sin procesar.",
      "Mínima compresión: ratio 2:1, attack lento 10ms.",
      "El groove viene del timing, no del sonido: usa Ableton Groove Pool.",
      "Groove: Swing 54–56% para feeling más humano.",
      "Sin sidechain agresivo — los elementos coexisten.",
    ],
    abletonParams: {
      compression: "ratio 2:1, attack 10ms",
      groove: "Swing 54–56%",
    },
    relatedIds: ["dub-techno-kick", "minimal-arrangement"],
  },

  // ── SOUND DESIGN ──────────────────────────────────────────────────
  {
    id: "dub-chord",
    title: "Dub Techno Chord",
    category: "SOUND DESIGN",
    subgenre: "Dub Techno",
    level: "intermediate",
    bpm: "120–128",
    time: "20 min",
    description: "Los acordes flotantes y reverberantes del dub techno. Wolfgang Voigt en su mejor momento.",
    steps: [
      "Instrumento: Operator con oscilador simple, forma de onda sine o triangle.",
      "Ataque largo: 50–200ms, decay corto, sustain al 70%, release largo 1–2s.",
      "Filtra con un LPF: cutoff en 600–800 Hz, resonancia baja.",
      "Añade chorus muy sutil para ampliar el stereo.",
      "Send a reverb masivo: decay 6–8s, pre-delay 30ms, mix 60%.",
      "Send a delay: 3/8 sincronizado, feedback 35%, filtro en ambos lados.",
      "Automatiza el cutoff del filtro muy lentamente a lo largo de 8 o 16 barras.",
    ],
    abletonParams: {
      envelope: "attack 50–200ms, release 1–2s",
      filter: "LPF, cutoff 600–800 Hz",
      reverb: "decay 6–8s, pre-delay 30ms, mix 60%",
      delay: "3/8 sync, feedback 35%",
    },
    relatedIds: ["dub-techno-kick", "melodic-techno-kick"],
  },
  {
    id: "acid-bassline",
    title: "Acid Bassline 303 Style",
    category: "SOUND DESIGN",
    subgenre: "Acid Techno",
    level: "intermediate",
    bpm: "130–140",
    time: "25 min",
    description: "El squelch del 303 que construyó el acid. Sin el original, con Ableton.",
    steps: [
      "Instrumento: Analog o un plugin que emule el 303 (p.ej. TAL-BassLine).",
      "Forma de onda: sawtooth.",
      "Envelope del filtro (Env Amount): al 60–80%, decay corto 100–200ms.",
      "Filtro LPF: cutoff inicial bajo en 200–400 Hz, resonancia alta 70–80%.",
      "Pitchbend: activa slides entre notas en el piano roll.",
      "Distorsión suave (Saturator) para añadir grit.",
      "Pattern de 16 pasos: usa octavas, slides, y accents para variedad.",
      "Automatiza cutoff y resonancia para que evolucione.",
    ],
    abletonParams: {
      waveform: "sawtooth",
      filterEnv: "amount 60–80%, decay 100–200ms",
      filter: "LPF, resonance 70–80%",
      saturator: "subtle, drive 20–30%",
    },
    relatedIds: ["dark-techno-kick", "industrial-synth"],
  },
  {
    id: "industrial-synth",
    title: "Industrial White Noise Synth",
    category: "SOUND DESIGN",
    subgenre: "Industrial Techno",
    level: "advanced",
    bpm: "140–150",
    time: "30 min",
    description: "Texturas de ruido oscuras y amenazantes. El sonido de las fábricas.",
    steps: [
      "Fuente: Operator con oscilador de ruido blanco (noise).",
      "Filtra con BPF: dos instancias apiladas, frecuencias distintas.",
      "LFO modulando el cutoff a velocidad lenta (0.1–0.5 Hz).",
      "Saturación extrema: Saturator en hard clip.",
      "Grain Delay para granularizar el ruido.",
      "Automatiza el pitch del Grain Delay para crear movimiento.",
      "Reverb corta con pre-delay 0ms para mantener la agresividad.",
      "Sidechain al kick: ratio 8:1, attack 0ms, release 80ms.",
    ],
    abletonParams: {
      source: "Operator noise oscillator",
      filter: "BPF stacked x2",
      lfo: "cutoff mod, 0.1–0.5 Hz",
      saturator: "hard clip",
      grainDelay: "automated pitch",
      sidechain: "ratio 8:1, attack 0ms, release 80ms",
    },
    relatedIds: ["industrial-kick", "tension-build"],
  },
  {
    id: "rumble-sub",
    title: "Kick Rumble Sub",
    category: "SOUND DESIGN",
    subgenre: "Dark Techno",
    level: "intermediate",
    bpm: "130–140",
    time: "15 min",
    description: "La capa de sub que hace vibrar el suelo. El secreto del low-end poderoso.",
    steps: [
      "Capa adicional bajo el kick principal: sine wave en Operator, pitch en 40–50 Hz.",
      "Envelope: ataque 0ms, decay largo 400–600ms, sustain 0.",
      "Este sine da el peso real — el kick por encima da el ataque.",
      "Sidechain: misma compresión que el kick principal.",
      "High-pass el kick principal en 60 Hz para que no choquen.",
      "Low-pass el rumble en 80 Hz para que no interfiera con el mid-range.",
      "Comprimir el bus de kicks (kick + rumble) juntos: ratio 3:1.",
    ],
    abletonParams: {
      subPitch: "40–50 Hz sine",
      envelope: "attack 0ms, decay 400–600ms",
      highPass: "kick HPF at 60 Hz",
      lowPass: "rumble LPF at 80 Hz",
      busCompression: "ratio 3:1",
    },
    relatedIds: ["dark-techno-kick", "hard-techno-kick"],
  },

  // ── ARRANGEMENT ───────────────────────────────────────────────────
  {
    id: "club-structure",
    title: "Club-Ready Track Structure",
    category: "ARRANGEMENT",
    subgenre: "Techno General",
    level: "beginner",
    bpm: "128–140",
    time: "30 min",
    description: "La estructura que funciona en clubs. De 6 a 8 minutos, diseñada para DJs.",
    steps: [
      "INTRO (0–2 min): solo kick + elementos percusivos. DJ mezcla aquí.",
      "BUILD 1 (2–3 min): entra bassline, hi-hats. Tensión creciente.",
      "DROP 1 (3–4 min): todos los elementos principales. Máxima energía.",
      "BREAKDOWN (4–5 min): retira kick, deja solo atmósferas y texturas.",
      "BUILD 2 (5–6 min): re-introduce elementos gradualmente, tensión máxima.",
      "DROP 2 (6–7 min): drop más intenso que el primero. Variación del tema.",
      "OUTRO (7–8 min): strip-down gradual. Solo kick al final. DJ mezcla aquí.",
    ],
    abletonParams: {
      totalLength: "6–8 min",
      barLength: "8 o 16 bars por sección",
      intro: "0–2 min, kick only",
      outro: "kick only for mixing",
    },
    relatedIds: ["tension-build", "minimal-arrangement"],
  },
  {
    id: "tension-build",
    title: "Tension & Release Build",
    category: "ARRANGEMENT",
    subgenre: "Dark Techno",
    level: "intermediate",
    bpm: "130–140",
    time: "20 min",
    description: "Cómo crear tensión insoportable y liberarla con precisión quirúrgica.",
    steps: [
      "8 barras antes del drop: sube el filtro HPF del bus master gradualmente (no automáticamente).",
      "Reduce el volumen del kick al 60% en las últimas 4 barras.",
      "Añade un noise riser: sine sweep de 20 Hz a 20 kHz en 8 barras.",
      "Reverb en todo el bus: decaída larga, sube el wet del 0 al 40% en 4 barras.",
      "En la barra 7: silencia todo excepto el riser.",
      "DROP: kick vuelve a volumen completo, HPF baja, reverb corta.",
      "Primer beat del drop: sin reverb larga — solo punch seco.",
    ],
    abletonParams: {
      hpfAutomation: "master bus, cut to 500 Hz",
      riser: "sine sweep 20 Hz → 20 kHz",
      reverbWet: "0% → 40% over 4 bars",
      dropTreatment: "dry kick, no reverb tail",
    },
    relatedIds: ["club-structure", "industrial-synth"],
  },
  {
    id: "minimal-arrangement",
    title: "Minimal Techno Arrangement",
    category: "ARRANGEMENT",
    subgenre: "Minimal Techno",
    level: "intermediate",
    bpm: "128–132",
    time: "25 min",
    description: "Decir más con menos. El arte de la subtracción en el techno.",
    steps: [
      "Empieza con 4 elementos máximo: kick, hat, bassline, pad.",
      "Cambia UN solo elemento cada 4 o 8 barras.",
      "El interés viene de micro-variaciones, no de nuevos sonidos.",
      "Usa automation para modular filtros muy lentamente: 0.1 Hz de cambio.",
      "Introduce percusiones secundarias solo en los breaks.",
      "La ausencia de elementos ES el break — no necesitas sweeps.",
      "Mantén la kick groove constante durante todo el track.",
    ],
    abletonParams: {
      maxElements: "4 simultaneous",
      changeRate: "1 element per 4–8 bars",
      filterMod: "0.1 Hz LFO on cutoff",
    },
    relatedIds: ["club-structure", "minimal-kick"],
  },

  // ── DJ STYLES (Pro) ───────────────────────────────────────────────
  {
    id: "charlotte-style",
    title: "Charlotte de Witte Style",
    category: "DJ STYLES",
    subgenre: "Raw Techno",
    level: "advanced",
    bpm: "138–142",
    time: "35 min",
    description: "Kick + hihat minimalista, drop sin melodía, BPM 138–142, rígido y oscuro.",
    steps: [
      "BPM: 138–142, nunca bajes de 135.",
      "Kick de dark techno: ver técnica Dark Techno Kick.",
      "Hi-hat patrón rígido: 8th notes, casi sin humanización.",
      "Cero melodía en el drop — solo ritmo y texturas.",
      "Bassline: una nota, movimiento en el filtro.",
      "Capas de ruido: 2–3 capas de noise filtrado, cada una con LFO diferente.",
      "Reverb en los elements percusivos, no en el kick.",
      "Arrangement tipo Charlotte: muy largo intro, caída brutal.",
    ],
    abletonParams: {
      bpm: "138–142",
      hihat: "8th notes, swing 50%",
      bassline: "one note, filter automation",
      noiseLayer: "2–3 filtered noise, different LFOs",
    },
    isPro: true,
    relatedIds: ["dark-techno-kick", "club-structure"],
  },
  {
    id: "amelie-lens-style",
    title: "Amelie Lens Style",
    category: "DJ STYLES",
    subgenre: "Hypnotic Techno",
    level: "advanced",
    bpm: "133–136",
    time: "35 min",
    description: "BPM 135, claps furiosos, reverb en todo, intensidad máxima.",
    steps: [
      "BPM: 133–136, energía constante.",
      "Clap en cada 2do y 4to beat: saturado, reverb larga.",
      "Reverb en casi todos los elementos: crea sensación de sala grande.",
      "Kick con punch fuerte pero sidechain no agresivo.",
      "Melodías: simples, oscuras, una nota cada 4 beats.",
      "Hi-hats: 16th notes con variaciones de velocidad.",
      "La intensidad viene de la densidad, no de la distorsión.",
      "Breaks: reverb explosion — todos los elementos en reverb larga simultáneamente.",
    ],
    abletonParams: {
      bpm: "133–136",
      clap: "beats 2 & 4, saturated, long reverb",
      hihat: "16th notes, velocity variation",
      reverbWet: "high on most elements",
    },
    isPro: true,
    relatedIds: ["dark-techno-kick", "tension-build"],
  },
  {
    id: "ben-klock-style",
    title: "Ben Klock Style",
    category: "DJ STYLES",
    subgenre: "Deep Techno",
    level: "advanced",
    bpm: "130–136",
    time: "40 min",
    description: "Minimalismo extremo, texturas industriales, largo desarrollo.",
    steps: [
      "BPM: 130–136. Más lento que Charlotte, más profundo.",
      "Kick limpio y poderoso: sin distorsión, mucho sub.",
      "Texturas industriales: grabaciones de maquinaria, loops de fábrica.",
      "Muy pocas notas musicales — el track vive en el ritmo y la textura.",
      "Desarrollo extremadamente lento: elementos entran cada 16–32 barras.",
      "El drop llega tarde — a veces en el minuto 5 o 6.",
      "Sin muchas capas simultáneas — la profundidad viene de la reverb.",
      "Atmósferas largas y oscuras en los breaks.",
    ],
    abletonParams: {
      bpm: "130–136",
      textureSource: "industrial recordings, factory loops",
      arrangementPacing: "elements every 16–32 bars",
      reverbDecay: "long, 4–8s on atmospheres",
    },
    isPro: true,
    relatedIds: ["dark-techno-kick", "minimal-arrangement"],
  },
  {
    id: "adam-beyer-style",
    title: "Adam Beyer / Drumcode Style",
    category: "DJ STYLES",
    subgenre: "Techno (Peak Time)",
    level: "intermediate",
    bpm: "134–140",
    time: "30 min",
    description: "Producción limpia, kicks potentes, melodías sutiles, accesible pero poderoso.",
    steps: [
      "BPM: 134–140, peak time.",
      "Kick: potente, limpio, mid-range presente (no solo sub).",
      "Producción hi-fi: mucho headroom, mix limpio.",
      "Melodías permitidas: oscuras pero reconocibles.",
      "Claps y snares definidos, no enterrados en reverb.",
      "Sidechain más pronunciado que en el dark techno: ratio 4:1.",
      "Hihat syncopado para crear groove.",
      "Estructura de 6–7 minutos: más accesible para sets comerciales.",
    ],
    abletonParams: {
      bpm: "134–140",
      kick: "clean, mid-range present",
      sidechain: "ratio 4:1, medium release",
      hihat: "syncopated pattern",
    },
    isPro: true,
    relatedIds: ["dark-techno-kick", "club-structure"],
  },

  // ── TECH HOUSE ────────────────────────────────────────────────────
  {
    id: "tech-house-kick",
    title: "Tech House Kick",
    category: "DRUMS",
    subgenre: "Tech House",
    level: "beginner",
    bpm: "120–128",
    time: "10 min",
    description: "Punchy y limpio. El kick que deja espacio al bassline.",
    steps: [
      "Kick punchy y limpio — evita sub excesivo porque el bassline lleva el low end.",
      "Transiente corto y presente: attack mínimo, decay 200–300ms.",
      "EQ: boost en 60 Hz para punch, corta en 150–300 Hz para claridad.",
      "Compresión suave: ratio 3:1, attack 5ms, release auto.",
      "Sidechain el bassline al kick con LFO Tool o VolumeShaper para el pump característico.",
      "Sin reverb — el kick tech house es seco y directo.",
    ],
    abletonParams: {
      bpm: "120–126",
      sidechain: "LFO Tool, sync to kick",
      eq: "boost 60 Hz, cut 150–300 Hz",
    },
    relatedIds: ["tech-house-bassline", "adam-beyer-style"],
  },
  {
    id: "tech-house-bassline",
    title: "Tech House Bassline (Chris Lake Style)",
    category: "SOUND DESIGN",
    subgenre: "Tech House",
    level: "intermediate",
    bpm: "120–126",
    time: "25 min",
    description: "Profundo, plucky y con groove propio. El centro del tech house.",
    steps: [
      "Serum: onda de sierra (saw wave) como oscilador principal.",
      "Filter: low pass con cutoff en 500 Hz, resonancia baja.",
      "Automatiza el cutoff con LFO sincronizado a 1/8 o 1/16 para movimiento.",
      "Añade portamento entre notas para slides orgánicos.",
      "Cadena de procesado: Compressor → Saturator (soft clip) → EQ → OTT al 15%.",
      "Sidechain al 100% con el kick para que el bassline se aparte en cada golpe.",
      "Patrón sincopado: notas en off-beats, velocidad alta en las que coinciden con el kick.",
      "Resultado: bassline profundo, plucky y con groove propio.",
    ],
    abletonParams: {
      waveform: "saw wave",
      filter: "LPF, cutoff 500 Hz",
      lfoRate: "1/8 or 1/16 sync",
      ott: "15%",
    },
    relatedIds: ["tech-house-kick", "fisher-style"],
  },
  {
    id: "tech-house-vocal-chop",
    title: "Vocal Chop Hook",
    category: "SOUND DESIGN",
    subgenre: "Tech House",
    level: "intermediate",
    time: "20 min",
    description: "El hook que se queda en la cabeza. Construido desde una vocal.",
    steps: [
      "Toma un sample vocal de 1–2 segundos.",
      "Córtalo en Simpler o en el clip de Ableton en slices pequeños.",
      "Pitch shift algunos slices +/- 3–5 semitonos para variación.",
      "Añade delay 1/8 con 20% feedback para que se repita sin saturar.",
      "Formant preservation: mantén el formant original para que no suene artificial.",
      "Automatiza el volumen de slices específicos para crear el hook.",
      "Reverb plate corta en send para dar espacio sin ensuciarlo.",
    ],
    abletonParams: {
      pitchShift: "+/- 3–5st",
      delay: "1/8, feedback 20%",
      reverb: "plate, short, send",
    },
    relatedIds: ["tech-house-bassline", "fisher-style"],
  },

  // ── DEEP HOUSE ────────────────────────────────────────────────────
  {
    id: "deep-house-kick",
    title: "Deep House Kick",
    category: "DRUMS",
    subgenre: "Deep House",
    level: "beginner",
    bpm: "118–124",
    time: "10 min",
    description: "Suave, cálido y con sub. El kick que invita a cerrar los ojos.",
    steps: [
      "Kick suave con sub prominente — 909 o 808 como base.",
      "Pitch bajo: -8 a -10 semitonos para calidez.",
      "Ataque lento (10–15ms) para punch sin agresividad.",
      "Sub: boost importante en 50–60 Hz, todo limpio.",
      "Reverb room muy corta (0.3s) para dar naturalidad.",
      "Sin saturación — el deep house es cálido, no distorsionado.",
      "Sidechain muy suave: ratio 2:1, release lento 300ms.",
    ],
    abletonParams: {
      pitch: "-8 to -10st",
      attack: "10–15ms",
      reverb: "room, decay 0.3s",
      sidechain: "ratio 2:1, release 300ms",
    },
    relatedIds: ["deep-house-bassline", "deep-house-pad"],
  },
  {
    id: "deep-house-bassline",
    title: "Deep House Bassline",
    category: "SOUND DESIGN",
    subgenre: "Deep House",
    level: "beginner",
    time: "15 min",
    description: "Redondo, suave, hipnótico. Menos es más.",
    steps: [
      "Bass con onda sinusoidal o triangular — suave y redondo.",
      "Octava baja: notas entre C1 y G1 para profundidad.",
      "Patrón sencillo y repetitivo: menos es más en deep house.",
      "Chorus sutil (10% wet) para dar amplitud sin perder definición.",
      "EQ: corta por encima de 200 Hz para no competir con mid-range.",
      "Compresión suave: el bassline deep house respira, no bombea.",
    ],
    abletonParams: {
      waveform: "sine or triangle",
      range: "C1–G1",
      chorus: "10% wet",
      eq: "cut >200 Hz",
    },
    relatedIds: ["deep-house-kick", "deep-house-pad"],
  },
  {
    id: "deep-house-pad",
    title: "Deep House Rhodes / Pad",
    category: "SOUND DESIGN",
    subgenre: "Deep House",
    level: "intermediate",
    time: "20 min",
    description: "Calor y profundidad emocional. La atmósfera del deep house.",
    steps: [
      "Rhodes o pad con Ableton Electric o Wavetable.",
      "Acorde en posición estrecha, notas medias (C3–C4).",
      "Reverb larga: decay 3–4s, pre-delay 30ms.",
      "Chorus suave para amplitud estéreo.",
      "Automatiza el filter cutoff muy lentamente durante el track.",
      "Volumen bajo en el mix — el pad es atmósfera, no protagonista.",
      "Resultado: calor y profundidad emocional característica del deep house.",
    ],
    abletonParams: {
      range: "C3–C4",
      reverb: "decay 3–4s, pre-delay 30ms",
      filterMod: "slow automation",
    },
    relatedIds: ["deep-house-kick", "deep-house-bassline"],
  },

  // ── HARDGROOVE ────────────────────────────────────────────────────
  {
    id: "hardgroove-kick",
    title: "Hardgroove Kick",
    category: "DRUMS",
    subgenre: "Hardgroove",
    level: "intermediate",
    bpm: "135–145",
    time: "20 min",
    description: "Potente y percusivo. El kick que dialoga con los loops tribales.",
    steps: [
      "Kick con punch fuerte y sub contenido — no tan extremo como hard techno.",
      "BPM 138 como referencia de partida.",
      "Percusión latina o tribal en loops: timestretch al BPM del proyecto.",
      "Los loops de percusión dan el groove — no el kick solo.",
      "Distorsión leve en la percusión para 'crunchy feel' característico.",
      "Sidechain con ride: compresión keyed al kick para que el ride 'pump'.",
      "Variación cada 8 bars: kick repeat al final para mantener energía.",
      "Swing en el groove pool: 52–54% para humanización.",
    ],
    abletonParams: {
      bpm: "138",
      swing: "52–54%",
      sidechain: "ride keyed to kick",
    },
    relatedIds: ["hardgroove-bassline", "chlär-style"],
  },
  {
    id: "hardgroove-bassline",
    title: "Hardgroove Rolling Bass",
    category: "SOUND DESIGN",
    subgenre: "Hardgroove",
    level: "intermediate",
    time: "20 min",
    description: "Tribal, rodante y percusivo. El bajo que es también ritmo.",
    steps: [
      "Bassline rolling y tribal — complementa la percusión latina.",
      "Oscilador: saw wave + sub sine en cadena paralela.",
      "Filtro con resonancia media, cutoff automation rítmica.",
      "Distorsión ligera para grit sin perder groove.",
      "Patrón sincopado que dialogue con los loops de percusión.",
      "Chlär / Stef Mendesidis style: bassline percusiva, casi rítmica en sí misma.",
    ],
    abletonParams: {
      waveform: "saw + sub sine parallel",
      filter: "medium resonance, rhythmic cutoff",
      distortion: "light",
    },
    relatedIds: ["hardgroove-kick", "chlär-style"],
  },

  // ── HARD HOUSE ────────────────────────────────────────────────────
  {
    id: "hard-house-kick",
    title: "Hard House Kick",
    category: "DRUMS",
    subgenre: "Hard House",
    level: "intermediate",
    bpm: "145–155",
    time: "20 min",
    description: "Stomping pero con bounce. El kick que hace mover los pies.",
    steps: [
      "Kick potente con bounce y groove — diferente al hard techno (menos agresivo).",
      "BPM 150 como referencia.",
      "4/4 stomping: cada beat claro y definido.",
      "Sidechain bass al kick con LFO Tool: ratio -4, ajusta para que no choquen.",
      "Multiband compression en el kick para más punch.",
      "El kick en hard house tiene más 'groove' que en hard techno — no tan rígido.",
      "Capa de kick: punch layer encima del kick principal para definición en el ataque.",
    ],
    abletonParams: {
      bpm: "150",
      sidechain: "LFO Tool, ratio -4",
      layer: "punch layer on top",
    },
    relatedIds: ["hard-house-bassline", "hard-techno-kick"],
  },
  {
    id: "hard-house-bassline",
    title: "Hard House Bouncy Bass",
    category: "SOUND DESIGN",
    subgenre: "Hard House",
    level: "intermediate",
    bpm: "145–155",
    time: "20 min",
    description: "El corazón del hard house: brinca sobre el kick.",
    steps: [
      "Bassline sincopada y bouncy — este es el corazón del hard house.",
      "Onda: sawtooth o square con filtro agresivo.",
      "Nota recomendada: D como root (evita choque con el kick).",
      "Bass shots cortos: decay muy corto, corta el sustain con cross-fade.",
      "Dobla la nota en octavas diferentes para capas: una en lo bajo, otra en mid.",
      "Sidechain al kick para el pump característico.",
      "Resultado: bajo que 'brinca' sobre el kick en cada bar.",
    ],
    abletonParams: {
      waveform: "sawtooth or square",
      rootNote: "D",
      decay: "short, cross-fade sustain",
      octaveLayers: "low + mid",
    },
    relatedIds: ["hard-house-kick", "hard-techno-kick"],
  },

  // ── HYPNOTIC TECHNO ───────────────────────────────────────────────
  {
    id: "hypnotic-kick",
    title: "Hypnotic Techno Kick",
    category: "DRUMS",
    subgenre: "Hypnotic Techno",
    level: "intermediate",
    bpm: "132–138",
    time: "15 min",
    description: "Meditativo, constante, hipnótico. La repetición como herramienta.",
    steps: [
      "Kick repetitivo e hipnótico — el kick es meditativo, no agresivo.",
      "Pitch medio-bajo: -8 semitonos.",
      "Mínima variación en el patrón: la hipnosis viene de la repetición.",
      "Añade micro-variaciones de volumen (±1–2 dB) para que respire.",
      "Reverb muy sutil en send — crea espacio sin ensuciar.",
      "Complementa con hi-hat en 16ths de forma mecánica y constante.",
    ],
    abletonParams: {
      pitch: "-8st",
      volumeVariation: "+/- 1–2 dB",
      reverb: "subtle send",
      hihat: "16ths, mechanical",
    },
    relatedIds: ["amelie-lens-style", "dark-techno-kick"],
  },

  // ── ACID TECHNO ───────────────────────────────────────────────────
  {
    id: "acid-303-bassline",
    title: "Acid 303 Bassline",
    category: "SOUND DESIGN",
    subgenre: "Acid Techno",
    level: "intermediate",
    bpm: "130–140",
    time: "25 min",
    description: "El squelch inconfundible del acid. Sin el 303 original.",
    steps: [
      "Ableton: usa Analog o un plugin 303 como TAL-BassLine-101 (gratis).",
      "Oscilador: square wave o sawtooth.",
      "Filtro: low pass con cutoff bajo (200–400 Hz) y resonancia alta (60–80%).",
      "Automatiza el cutoff y la resonancia durante el track — esto es el acid.",
      "Accent: aumenta el volumen de notas específicas para el patrón característico.",
      "Slide/glide: portamento entre notas para el efecto slide del 303.",
      "Distorsión leve post-filtro para grit analógico.",
      "Patrón: secuencia de 16 pasos, notas cortas y staccato principalmente.",
    ],
    abletonParams: {
      waveform: "square or saw",
      filter: "LPF, cutoff 200–400 Hz, resonance 60–80%",
      portamento: "between notes",
      steps: "16-step sequence",
    },
    relatedIds: ["acid-bassline", "dark-techno-kick"],
  },

  // ── EBM ───────────────────────────────────────────────────────────
  {
    id: "ebm-kick",
    title: "EBM / Body Music Kick",
    category: "DRUMS",
    subgenre: "EBM",
    level: "advanced",
    bpm: "128–140",
    time: "25 min",
    description: "Sintético, industrial, robótico. El kick que construyó el EBM.",
    steps: [
      "Kick sintético — no usa samples de batería real.",
      "Síntesis: Ableton Operator con oscilador sine, pitch envelope pronunciado.",
      "Pitch envelope: comienza en 200 Hz, cae a 50 Hz en 50ms.",
      "Distorsión intensa: Saturator en modo Hard Clip.",
      "Sin reverb — el EBM kick es brutal y seco.",
      "Combina con bassline industrial mecánica.",
      "Resultado: kick sintético agresivo, industrial, robótico.",
    ],
    abletonParams: {
      source: "Operator, sine oscillator",
      pitchEnv: "200 Hz → 50 Hz in 50ms",
      saturator: "Hard Clip",
    },
    relatedIds: ["industrial-kick", "industrial-synth"],
  },

  // ── MIXING ────────────────────────────────────────────────────────
  {
    id: "industrial-mix",
    title: "Industrial Techno Mixing",
    category: "MIXING",
    subgenre: "Industrial Techno",
    level: "advanced",
    time: "40 min",
    description: "El objetivo no es que suene limpio. Es que suene deliberadamente roto.",
    steps: [
      "El objetivo no es que suene 'limpio' sino 'deliberadamente roto'.",
      "Saturación en casi todos los canales — es parte del sonido.",
      "Bus de drums: compresión agresiva ratio 8:1, el bus aplasta.",
      "Low end: HPF en todo excepto kick y bass — espacio limpio en sub.",
      "Mid range: denso y oscuro — no limpies demasiado.",
      "Reverb: larga y oscura en elementos secundarios.",
      "Referencia: Surgeon, Tommy Four Seven, Rebekah — mezclas crudas y agresivas.",
    ],
    abletonParams: {
      drumBus: "ratio 8:1",
      hpf: "all except kick and bass",
      reverb: "long, dark on secondary elements",
    },
    relatedIds: ["industrial-kick", "industrial-synth"],
  },

  // ── DJ STYLES adicionales ─────────────────────────────────────────
  {
    id: "fisher-style",
    title: "FISHER Style",
    category: "DJ STYLES",
    subgenre: "Tech House",
    level: "intermediate",
    bpm: "124–126",
    time: "35 min",
    description: "El groove es todo. El bajo hace el trabajo duro.",
    steps: [
      "BPM 124–126 — el groove es todo.",
      "Bassline: profunda, plucky, con mucho movimiento rítmico.",
      "Vocal hooks: procesa una vocal corta en múltiples slices, crea el hook con eso.",
      "Drops: simples pero impactantes — no sobrecargues de elementos.",
      "Referencia: tracks de Catch & Release, Stop It — minimalismo con energía máxima.",
      "Lo que define a FISHER: el bajo hace el trabajo duro, todo lo demás es apoyo.",
    ],
    abletonParams: {
      bpm: "124–126",
      bassline: "plucky, rhythmic movement",
      drop: "minimal, impactful",
    },
    isPro: true,
    relatedIds: ["tech-house-bassline", "tech-house-vocal-chop"],
  },
  {
    id: "john-summit-style",
    title: "John Summit Style",
    category: "DJ STYLES",
    subgenre: "Tech House",
    level: "beginner",
    bpm: "125–127",
    time: "30 min",
    description: "Accesible y groovy. Tech house con melodía memorable.",
    steps: [
      "BPM 125–127 — accesible y groovy.",
      "Melodía: simple y memorable — no más de 4–5 notas.",
      "Drums: punchy pero no agresivos, muy en el groove.",
      "Builds: filter sweep + riser de 8 a 16 bars.",
      "Drop: toda la energía de golpe — kick + bass + melodía juntos.",
      "Referencia: Deep End, La Danza — tech house con melodía accesible.",
    ],
    abletonParams: {
      bpm: "125–127",
      melody: "4–5 notes max",
      build: "filter sweep + riser 8–16 bars",
    },
    isPro: true,
    relatedIds: ["tech-house-kick", "fisher-style"],
  },
  {
    id: "chlär-style",
    title: "Chlär Style",
    category: "DJ STYLES",
    subgenre: "Hardgroove",
    level: "advanced",
    bpm: "138–142",
    time: "40 min",
    description: "La tensión viene del ritmo, no de synthlines.",
    steps: [
      "BPM 138–142 — rápido pero con swing.",
      "Percusión tribal como protagonista: loops con swing pronunciado.",
      "Bassline rolling que dialogue con la percusión.",
      "Casi sin melodía convencional — el groove ES la melodía.",
      "Referencia: Chlär tracks en labels como Mord — raw y percusivo.",
      "El secreto: la tensión viene del ritmo, no de synthlines.",
    ],
    abletonParams: {
      bpm: "138–142",
      swing: "pronounced",
      percussion: "tribal loops as lead",
    },
    isPro: true,
    relatedIds: ["hardgroove-kick", "hardgroove-bassline"],
  },

  // ── PLUGINS ───────────────────────────────────────────────────────
  {
    id: "serum-basics",
    title: "Serum: Guía Completa para Techno",
    category: "PLUGINS",
    subgenre: "All",
    level: "beginner",
    time: "30 min",
    description: "Todo lo que necesitas saber de Serum para producir techno desde cero.",
    steps: [
      "OSC A: tu sonido principal. Onda más usada en techno: Saw (serrada) para basses y leads.",
      "OSC B: capa o detuning. Sube Detune a 0.10–0.20 para engrosar el sonido.",
      "SUB: oscilador sine puro para refuerzo de sub-bass. Octava -1 siempre.",
      "NOISE: ruido blanco o de color para añadir textura. Muy útil en percusión.",
      "FILTER: low pass como default. Cutoff define el brillo, Resonance añade carácter.",
      "LFO: sincroniza al BPM para movimiento rítmico automático en el filtro.",
      "ENV 2: asigna al cutoff del filtro para que el sonido se abra al atacar.",
      "FX internos: Hyper/Dimension para amplitud, Reverb para espacio, Distort para grit.",
      "Tip: usa Wavetable position automation para que el sonido evolucione durante el track.",
    ],
    relatedIds: ["serum-kick", "serum-bassline", "serum-pad"],
  },
  {
    id: "serum-kick",
    title: "Serum: Kick Sintético desde Cero",
    category: "PLUGINS",
    subgenre: "All",
    level: "intermediate",
    time: "20 min",
    description: "Diseña tu propio kick 100% sintético sin samples de librería.",
    steps: [
      "OSC A: onda Sine en octava -2 para el body del kick.",
      "ENV 1 → Pitch: pitch envelope pronunciado. Start: +48st, caída en 50–80ms.",
      "Esta caída de pitch ES el kick — ajusta la velocidad para más o menos punch.",
      "NOISE: añade noise layer con envelope muy corto (10ms) para el click del ataque.",
      "FILTER: no necesario en kicks sintéticos simples.",
      "FX: Distort al 20–30% para carácter analógico.",
      "Export el kick como audio y procésalo en Ableton con EQ y compresión.",
      "Resultado: kick 100% tuyo, sin samples de librería.",
    ],
    relatedIds: ["serum-basics", "dark-techno-kick"],
  },
  {
    id: "serum-bassline",
    title: "Serum: Bassline Techno Perfecta",
    category: "PLUGINS",
    subgenre: "Dark Techno",
    level: "intermediate",
    time: "25 min",
    description: "De OSC a sidechain — el flujo completo de una bassline oscura.",
    steps: [
      "OSC A: Saw wave. OSC B: misma saw con Detune +0.15 para grosor.",
      "FILTER: Low Pass, cutoff en 300 Hz, resonancia al 20%.",
      "ENV 2 → Filter Cutoff: amount +40, decay 200ms para que el filtro se cierre.",
      "LFO 1 → Filter Cutoff: Rate 1/16, amount +10 para movimiento sutil.",
      "FX: Hyper al 10% para amplitud estéreo. Distort al 15% para grit.",
      "En Ableton: EQ → HPF en 30 Hz, boost en 80 Hz, Saturator → Compressor.",
      "Sidechain al kick: ratio 4:1, ataque 1ms, release 100ms.",
    ],
    abletonParams: {
      hpf: "30 Hz",
      boost: "80 Hz",
      sidechain: "ratio 4:1, attack 1ms, release 100ms",
    },
    relatedIds: ["serum-basics", "dark-techno-kick", "rumble-sub"],
  },
  {
    id: "serum-pad",
    title: "Serum: Pad Atmosférico Techno",
    category: "PLUGINS",
    subgenre: "Melodic Techno",
    level: "beginner",
    time: "20 min",
    description: "Un pad que evoluciona solo. Atmósfera sin esfuerzo.",
    steps: [
      "OSC A: Wavetable de tipo 'Analog' o 'Basic Shapes'. Detune +0.25.",
      "OSC B: mismo wavetable una octava arriba. Level más bajo (-6 dB).",
      "FILTER: Low Pass, cutoff en 1000 Hz, abre gradualmente con automation.",
      "ENV 1: attack largo (500ms), sustain alto, release largo (2s) para que fluya.",
      "LFO → Wavetable position: movimiento lento para que el timbre evolucione.",
      "FX: Reverb 40% wet, decay largo. Chorus para amplitud. Delay 1/4.",
      "Resultado: pad etéreo que evoluciona sin que tengas que tocarlo.",
    ],
    abletonParams: {
      filter: "LPF, cutoff 1000 Hz",
      envelope: "attack 500ms, release 2s",
      reverb: "40% wet",
      delay: "1/4 sync",
    },
    relatedIds: ["serum-basics", "deep-house-pad", "atmospheric-drone"],
  },
  {
    id: "tal-bassline-101",
    title: "TAL-BassLine-101: 303 Acid Gratis",
    category: "PLUGINS",
    subgenre: "Acid Techno",
    level: "beginner",
    time: "20 min",
    description: "El TB-303 gratis y perfecto. El squelch acid sin gastar nada.",
    steps: [
      "Descarga TAL-BassLine-101 — es gratis y replica el TB-303 perfectamente.",
      "Oscilador: alterna entre Saw y Square para diferentes texturas acid.",
      "CUTOFF: empieza bajo (20–30%) y automatiza hacia arriba durante el track.",
      "RESONANCE: 60–80% para el sonido acid característico.",
      "ENV MOD: controla cuánto afecta el envelope al filtro. Alto = más dramático.",
      "ACCENT: activa en notas específicas del step sequencer para el patrón 303.",
      "GLIDE: activa entre notas seleccionadas para el slide característico del acid.",
      "Secuencia de 16 pasos: mezcla notas cortas y largas, usa notas fuera de escala.",
    ],
    relatedIds: ["acid-bassline", "acid-303-bassline"],
  },
  {
    id: "vital-synth",
    title: "Vital: Alternativa Gratis a Serum",
    category: "PLUGINS",
    subgenre: "All",
    level: "beginner",
    time: "15 min",
    description: "Todo el poder de Serum, gratis. La herramienta que no conocías.",
    steps: [
      "Vital es 100% gratis y tiene capacidades similares a Serum.",
      "Descarga en vital.audio — versión gratis es más que suficiente.",
      "Interfaz visual: puedes dibujar tus propias wavetables.",
      "Spectral Morph: herramienta única — transforma el espectro en tiempo real.",
      "3 LFOs con formas personalizables — más flexibilidad que Serum.",
      "Efectos integrados: chorus, phaser, reverb, distortion, filter.",
      "Para techno: úsalo igual que Serum. Los conceptos son idénticos.",
      "Tip: descarga preset packs gratuitos en VitalTones.com.",
    ],
    relatedIds: ["serum-basics", "serum-bassline"],
  },
  {
    id: "operator-fm",
    title: "Ableton Operator: FM Synthesis para Techno",
    category: "PLUGINS",
    subgenre: "Industrial Techno",
    level: "advanced",
    time: "35 min",
    description: "Sonidos metálicos e industriales únicos. La síntesis FM dominada.",
    steps: [
      "Operator es el synth FM de Ableton — perfecto para sonidos metálicos e industriales.",
      "FM synthesis: un oscilador (Modulador) modifica el timbre de otro (Carrier).",
      "Para percusión metálica: algorithm A→B, ratio alto en el modulador (7–14).",
      "Para kicks sintéticos: ratio bajo (1–2), pitch envelope en el carrier.",
      "Para hi-hats: múltiples osciladores con ratios inarmónicos (7, 11, 13).",
      "Para leads industriales: detuning entre operadores + distorsión externa.",
      "Clave FM: a más Amount del modulador, más complejo y metálico el sonido.",
      "Referencia: Ableton tiene preset packs FM específicos para techno — explóralos.",
    ],
    relatedIds: ["industrial-synth", "ebm-kick"],
  },

  // ── DRUMS EXPANDIDO ───────────────────────────────────────────────
  {
    id: "hihat-closed-techno",
    title: "Closed Hi-Hat: Técnicas por Subgénero",
    category: "DRUMS",
    subgenre: "All",
    level: "beginner",
    time: "12 min",
    description: "El hi-hat correcto para cada estilo. Un elemento, siete enfoques.",
    steps: [
      "Dark Techno: hi-hat en 8ths, seco, casi sin reverb. Volumen moderado.",
      "Tech House: hi-hat 16ths con swing del 52–54%, shaker en off-beats.",
      "Industrial: hi-hat distorsionado, Overdrive al 40%, mecánico y rígido.",
      "Hypnotic: hi-hat constante en 16ths, volumen igual en todas las notas.",
      "Hardgroove: hi-hat con micro-timing humanizado, usa Groove Pool.",
      "Minimal: hi-hat esporádico, cada 2–4 beats, deja espacio al kick.",
      "Procesado universal: transient designer (attack +3 dB), EQ (HPF en 8 kHz para brillo).",
      "Variación de velocidad: nunca todas las notas al mismo volumen — aburrido.",
    ],
    relatedIds: ["hihat-open", "drum-programming-groove"],
  },
  {
    id: "hihat-open",
    title: "Open Hi-Hat: Cómo Usarlo en Techno",
    category: "DRUMS",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "El 'aire' del track. Saber cuándo y cómo abrirlo.",
    steps: [
      "El open hi-hat define el 'aire' y energía de un track.",
      "Posición: off-beats (entre golpes del kick), o en el 2 y 4 del bar.",
      "Decay: corto para más control, largo para más apertura y energía.",
      "Dark Techno: muy seco, decay corto 200ms, volumen bajo.",
      "Tech House: con reverb plate corta, más presente y 'groovy'.",
      "Hard Techno: con distorsión, agresivo, decay medio 400ms.",
      "Relleno: usa open hi-hat al final de cada 4 u 8 bars para marcar transiciones.",
      "Tip: el old/new open hi-hat alterna para humanización.",
    ],
    relatedIds: ["hihat-closed-techno", "clap-snare-techno"],
  },
  {
    id: "clap-snare-techno",
    title: "Clap y Snare: Layering Profesional",
    category: "DRUMS",
    subgenre: "All",
    level: "intermediate",
    time: "20 min",
    description: "Un solo sample suena plano. Las capas hacen la diferencia.",
    steps: [
      "Un solo clap o snare suena plano — siempre usa capas (layering).",
      "Capa 1: el body (cuerpo) — sample con mucho sub y cuerpo, volumen alto.",
      "Capa 2: el snap (chasquido) — sample agudo y corto para definición.",
      "Capa 3: noise tail — ruido blanco muy corto para textura.",
      "EQ en cada capa: separa frecuencias para que no compitan entre sí.",
      "Reverb: manda todas las capas al mismo reverb send para cohesión.",
      "Posición: beat 2 y 4 en la mayoría de subgéneros.",
      "Dark Techno: snare muy reverberado, casi atmosférico.",
      "Amelie Lens style: clap furioso, reverb larga, en todos los tiempos.",
    ],
    relatedIds: ["hihat-closed-techno", "drum-bus-processing"],
  },
  {
    id: "percussion-layers",
    title: "Percusiones: Congas, Toms, Shakers",
    category: "DRUMS",
    subgenre: "All",
    level: "intermediate",
    time: "20 min",
    description: "Más allá del kick y el hat. Las percusiones que dan vida al groove.",
    steps: [
      "Las percusiones dan groove y humanidad — los drums no son solo kick+hat.",
      "Congas: dan feeling tribal. Úsalas en hardgroove y hypnotic techno.",
      "Shakers: llenan el espacio de alta frecuencia. Alternativa a hi-hats constantes.",
      "Toms: para fills y transiciones. Un tom en el beat 4 del bar es suficiente.",
      "Rimshots: sonido metálico agudo. Perfecto para dark techno y EBM.",
      "Cowbell: suena ridículo pero funciona filtrado y procesado en techno minimal.",
      "Procesado: todas las percusiones necesitan HPF (quita sub) y compresión suave.",
      "Tip: timestretch loops de percusión latina a tu BPM — resultado único.",
    ],
    relatedIds: ["hardgroove-kick", "drum-programming-groove"],
  },
  {
    id: "drum-programming-groove",
    title: "Drum Programming: El Arte del Groove",
    category: "DRUMS",
    subgenre: "All",
    level: "intermediate",
    time: "25 min",
    description: "El groove no viene del sonido. Viene del timing y la velocidad.",
    steps: [
      "El groove no viene del sonido sino del TIMING y la VELOCIDAD de las notas.",
      "Velocity: varía entre 80–127 en notas importantes, 60–80 en notas secundarias.",
      "Micro-timing: desplaza notas ±5–10ms para humanización sin perder el click.",
      "Ableton Groove Pool: aplica grooves de Swing para feeling más natural.",
      "Swing: 50% = perfecto y rígido. 54–56% = groovy y humano. 60%+ = demasiado.",
      "Ghost notes: notas muy suaves (velocity 30–50) entre las principales dan profundidad.",
      "Pattern variation: cambia el patrón cada 8 o 16 bars — evita hipnosis negativa.",
      "Referencia: estudia el drum programming de Basic Channel para minimalismo máximo.",
    ],
    relatedIds: ["minimal-kick", "hihat-closed-techno"],
  },
  {
    id: "909-vs-808",
    title: "909 vs 808: Cuándo Usar Cada Uno",
    category: "DRUMS",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "Los dos kicks más usados en la historia electrónica. Cuál es el tuyo.",
    steps: [
      "Roland TR-909: el estándar del techno y house. Sonido más 'clicky' y presente.",
      "Roland TR-808: más sub y boom. Estándar en hip hop pero también en house.",
      "909 kick: más punch en el ataque, sube bien en un sistema de sonido grande.",
      "808 kick: más sub, mejor en géneros lentos. En techno puede ensuciarse.",
      "Para techno oscuro: 909 con pitch bajo (-8 a -12st) es el punto de partida.",
      "Para tech house: 909 con menos sub, más mid-range.",
      "Para deep house: 808 suavizado con reverb corta.",
      "Ableton: carga '909 Core Kit' o '808 Core Kit' en Drum Rack como punto de partida.",
      "Tip: mezcla elementos del 909 y 808 en layers para tu sonido único.",
    ],
    relatedIds: ["dark-techno-kick", "deep-house-kick"],
  },
  {
    id: "drum-bus-processing",
    title: "Drum Bus: Pegar el Kit",
    category: "DRUMS",
    subgenre: "All",
    level: "advanced",
    time: "20 min",
    description: "El proceso que hace que tu kit suene grabado junto, no elementos sueltos.",
    steps: [
      "Agrupa todos tus drums en un bus y procésalos juntos para cohesión.",
      "Ableton Drum Buss: herramienta específica. Drive al 10%, Crunch al 20%.",
      "Transient Shaper en el bus: attack -2 dB para suavizar, sustain +3 dB para cuerpo.",
      "Glue Compressor: ratio 2:1, attack 10ms, release auto. El más suave posible.",
      "EQ del bus: HPF en 30 Hz, boost sutil en 80 Hz, cut en 200–400 Hz si hay mud.",
      "Saturación suave en el bus: une el kit de forma natural.",
      "Compresión paralela (New York): mezcla 20% del bus comprimido agresivamente.",
      "Tip: un buen drum bus hace que el kit suene como grabado junto, no elementos sueltos.",
    ],
    abletonParams: {
      drumBuss: "drive 10%, crunch 20%",
      glueComp: "ratio 2:1, attack 10ms, release auto",
      eq: "HPF 30 Hz, boost 80 Hz, cut 200–400 Hz",
    },
    relatedIds: ["clap-snare-techno", "industrial-mix"],
  },

  // ── SOUND DESIGN EXPANDIDO ────────────────────────────────────────
  {
    id: "sub-bass-design",
    title: "Sub Bass: Cómo Hacerlo Correctamente",
    category: "SOUND DESIGN",
    subgenre: "All",
    level: "beginner",
    time: "15 min",
    description: "La frecuencia que se siente más que se oye. El fundamento de todo.",
    steps: [
      "El sub bass es la frecuencia que SIENTES más que oyes en un club.",
      "En Serum: solo Sub oscillator, onda Sine, octava -1.",
      "En Ableton: usa Operator con un solo oscilador Sine.",
      "Nota: root note de tu track, en el offbeat (después del kick).",
      "EQ: SOLO frecuencias entre 30–80 Hz. Corta todo lo demás.",
      "Mono: el sub bass siempre en mono. El stereo en sub causa problemas de fase.",
      "Sidechaining: compresión muy suave del sub al kick para que no choquen.",
      "Tip: si no tienes buenos monitores, usa auriculares para verificar el sub.",
    ],
    abletonParams: {
      range: "30–80 Hz only",
      mono: "always",
      sidechain: "soft, kick trigger",
    },
    relatedIds: ["rumble-sub", "serum-bassline"],
  },
  {
    id: "lead-synth-techno",
    title: "Lead Synth Techno: Diseño y Procesado",
    category: "SOUND DESIGN",
    subgenre: "Dark Techno",
    level: "intermediate",
    time: "25 min",
    description: "Esporádico, oscuro y efectivo. El lead que no roba protagonismo.",
    steps: [
      "El lead en techno es esporádico y oscuro — no es el protagonista.",
      "Serum: Saw wave + detuning ligero. Filter Low Pass con cutoff en 800 Hz.",
      "Automation del cutoff: abre durante el drop, cierra en el breakdown.",
      "Efecto: reverb media + delay 1/8 para que flote en el mix.",
      "Distorsión suave para grit industrial.",
      "Posición en el mix: mid-range, nunca compite con el kick ni el bass.",
      "Notas: pocas y deliberadas. Un riff de 4 notas repetido es suficiente.",
      "Dark reference: Surgeon, Perc — leads muy procesados, casi irreconocibles.",
    ],
    abletonParams: {
      filter: "LPF, cutoff 800 Hz",
      delay: "1/8 sync",
      reverb: "medium",
    },
    relatedIds: ["serum-basics", "atmospheric-drone"],
  },
  {
    id: "atmospheric-drone",
    title: "Drone y Atmósfera: Textura de Fondo",
    category: "SOUND DESIGN",
    subgenre: "Dark Techno",
    level: "beginner",
    time: "15 min",
    description: "La niebla que envuelve el track. Presente siempre, invisible casi siempre.",
    steps: [
      "El drone es la 'niebla' que envuelve el track — siempre presente pero invisible.",
      "Serum: pad con wavetable lento, mucho reverb y delay.",
      "O: graba ruido ambiente, procésalo con granular (Granulator II gratis en Ableton).",
      "Granular: grain size grande para textura suave, pequeño para efecto glitchy.",
      "EQ: corta todo por encima de 2 kHz y por debajo de 200 Hz — solo mid-range.",
      "Reverb muy larga (8–12s) para que se funda con el espacio.",
      "Volumen: muy bajo en el mix, casi imperceptible. Se nota cuando lo quitas.",
      "Automation: sube ligeramente durante breaks para más atmósfera.",
    ],
    abletonParams: {
      eq: "cut >2 kHz and <200 Hz",
      reverb: "8–12s decay",
    },
    relatedIds: ["serum-pad", "industrial-synth"],
  },
  {
    id: "riser-sweep",
    title: "Risers y Sweeps: Transiciones Profesionales",
    category: "SOUND DESIGN",
    subgenre: "All",
    level: "beginner",
    time: "15 min",
    description: "La carga antes de la explosión. El arte de la anticipación.",
    steps: [
      "El riser crea tensión antes del drop — es la 'carga' antes de la 'explosión'.",
      "Método 1: ruido blanco con filter automation. HPF sube de 200 Hz a 10 kHz en 8 bars.",
      "Método 2: Serum — sine wave con pitch automation (+24st en 4 bars).",
      "Método 3: reverb de un elemento existente reverse: exporta reverb, gírala al revés.",
      "Sweep: filter que baja (lowpass cerrándose) para crear tensión diferente.",
      "Duración: 4, 8 o 16 bars según la intensidad que buscas.",
      "Volumen: empieza casi inaudible, termina dominando el mix.",
      "Tip: automatiza el volumen del riser para que el crecimiento sea exponencial, no lineal.",
    ],
    relatedIds: ["tension-build", "breakdown-design"],
  },
  {
    id: "vocal-processing",
    title: "Vocals en Techno: Procesado Avanzado",
    category: "SOUND DESIGN",
    subgenre: "Tech House",
    level: "advanced",
    time: "30 min",
    description: "La vocal como elemento de groove, no de melodía.",
    steps: [
      "La vocal en tech house y techno es un elemento de groove, no de melodía.",
      "Grabación: seco y cercano al micrófono. Sin reverb en la grabación.",
      "Pitch correction: Ableton Tuner para verificar afinación. Auto-Filter para efecto.",
      "Formant shift: Ableton Pitch o Re-Pitch para cambiar el carácter sin cambiar el pitch.",
      "Chop: divide la vocal en slices de 1/8 o 1/16 en el clip de Ableton.",
      "Stutter: repite slices específicos para el efecto stutter característico.",
      "Reverb: muy poco — la vocal techno es seca y presente.",
      "Distorsión ligera para que se integre con el mix oscuro.",
      "FISHER style: una vocal de 2 palabras, choppeada en loop de 4 bars = hook completo.",
    ],
    relatedIds: ["tech-house-vocal-chop", "fisher-style"],
  },
  {
    id: "noise-design",
    title: "Ruido como Instrumento: Noise Design",
    category: "SOUND DESIGN",
    subgenre: "Industrial Techno",
    level: "intermediate",
    time: "25 min",
    description: "El ruido no es un error. En industrial techno, es el sonido.",
    steps: [
      "En industrial techno el ruido ES el sonido, no un error.",
      "Ruido blanco: todas las frecuencias igualmente. Base para hi-hats y texturas.",
      "Ruido rosa: más presencia en graves. Más 'orgánico' que el blanco.",
      "Ruido marrón: mucho sub. Perfecto como capa de bajo en industrial.",
      "Procesado: filtra el ruido para extraer rangos específicos de frecuencia.",
      "Envelopes cortos en el ruido = percusión sintética única.",
      "Granular sobre ruido grabado: resultado impredecible y único.",
      "Saturación extrema del ruido: de textura a distorsión total.",
      "Referencia: Raime, Demdike Stare — el ruido como lenguaje musical.",
    ],
    relatedIds: ["industrial-synth", "atmospheric-drone"],
  },

  // ── MIXING EXPANDIDO ──────────────────────────────────────────────
  {
    id: "eq-techno-fundamentals",
    title: "EQ en Techno: Fundamentos",
    category: "MIXING",
    subgenre: "All",
    level: "beginner",
    time: "20 min",
    description: "El EQ no quita frecuencias — crea espacio para cada elemento.",
    steps: [
      "EQ no es solo quitar frecuencias — es crear espacio para cada elemento.",
      "High Pass Filter (HPF): quita sub innecesario. Aplica en TODO excepto kick y bass.",
      "En voces, pads, hats: HPF en 80–100 Hz. Liberas espacio sin que suene diferente.",
      "Low Pass Filter (LPF): suaviza elementos demasiado brillantes.",
      "Boost con Q ancho (gentle): añade presencia natural.",
      "Cut con Q estrecho (surgical): elimina frecuencias problemáticas específicas.",
      "EQ complementario: si el kick tiene mucho en 80 Hz, el bass tiene menos ahí.",
      "Referencia A/B: compara con referencias profesionales cada 20 minutos.",
    ],
    relatedIds: ["compression-techno", "reference-track"],
  },
  {
    id: "compression-techno",
    title: "Compresión: Guía Práctica",
    category: "MIXING",
    subgenre: "All",
    level: "intermediate",
    time: "25 min",
    description: "La compresión no baja el volumen. Controla dinámicas y da punch.",
    steps: [
      "La compresión controla dinámicas y da punch — no es solo 'bajar el volumen'.",
      "Threshold: el nivel donde el compresor empieza a actuar.",
      "Ratio: cuánto comprime. 2:1 suave, 4:1 estándar, 10:1 agresivo, ∞:1 limiter.",
      "Attack: qué tan rápido reacciona. Lento (10–30ms) = preserva transiente. Rápido (1ms) = aplasta.",
      "Release: qué tan rápido deja de comprimir. Muy rápido = pumping. Auto = seguro.",
      "Para kicks: attack 1–5ms, release auto, ratio 4:1.",
      "Para buses: Glue Compressor, ratio 2:1, attack 10ms — lo más transparente posible.",
      "Compresión paralela: mezcla señal sin comprimir + señal muy comprimida = lo mejor de ambos.",
    ],
    abletonParams: {
      kickCompression: "ratio 4:1, attack 1–5ms, release auto",
      busCompression: "Glue, ratio 2:1, attack 10ms",
    },
    relatedIds: ["eq-techno-fundamentals", "sidechain-advanced"],
  },
  {
    id: "sidechain-advanced",
    title: "Sidechain: Más Allá del Pumping Básico",
    category: "MIXING",
    subgenre: "All",
    level: "intermediate",
    time: "20 min",
    description: "El pumping es la consecuencia. El sidechain es la herramienta.",
    steps: [
      "Sidechain estándar: bass se baja cuando entra el kick. Ratio 4:1, attack 1ms.",
      "Ghost sidechain: crea un kick MIDI silenciado como trigger — más control sin el kick real.",
      "LFO Tool: alternativa al compresor. Forma de volumen exacta sincronizada al BPM.",
      "VolumeShaper: similar a LFO Tool, más visual.",
      "Sidechain con Ableton: compressor → Sidechain → activar External → seleccionar kick.",
      "Sidechain en reverb sends: el reverb del kick se baja cuando entra el siguiente kick.",
      "Multiband sidechain: solo el rango bajo del bass se baja. Los mids permanecen audibles.",
      "Resultado: pumping controlado que da energía sin destrozar la mezcla.",
    ],
    relatedIds: ["compression-techno", "industrial-mix"],
  },
  {
    id: "stereo-imaging",
    title: "Stereo Imaging: Amplitud sin Problemas",
    category: "MIXING",
    subgenre: "All",
    level: "advanced",
    time: "20 min",
    description: "Ancho sin pérdida de compatibilidad mono. La regla de los 200 Hz.",
    steps: [
      "El techno de club debe ser MONO compatible — los sistemas de sonido son mono.",
      "Regla: todo por debajo de 200 Hz en MONO. Siempre.",
      "Mid/Side processing: procesa el centro (Mid) y los lados (Side) por separado.",
      "Haas effect: copia de un elemento desplazada 10–30ms en el canal opuesto.",
      "Chorus y phaser: amplitud estéreo natural sin causar problemas de fase.",
      "Verificación: usa el correlómetro de Ableton. Siempre positivo en el sub.",
      "Utility plugin: reduce el ancho estéreo del sub a mono con un click.",
      "Tip: un mix mono sólido que suena bien en mono → sonará increíble en stereo.",
    ],
    relatedIds: ["mastering-techno", "eq-techno-fundamentals"],
  },
  {
    id: "mastering-techno",
    title: "Mastering Techno: De Demo a Club",
    category: "MIXING",
    subgenre: "All",
    level: "advanced",
    time: "30 min",
    description: "No es magia. Es corrección y nivel. Aquí el proceso completo.",
    steps: [
      "El mastering en techno no es magia — es corrección y nivel.",
      "LUFS objetivo: -6 a -8 LUFS integrado para club. Streaming: -14 LUFS.",
      "Cadena básica: EQ → Compresión multibanda → Saturación → Limiter.",
      "EQ de mastering: muy suave. ±1.5 dB máximo en cualquier frecuencia.",
      "Saturación: une los elementos que no mezcló bien la mezcla.",
      "Limiter: true peak -0.3 dBTP para evitar clipping en streaming.",
      "Ableton: Glue Compressor → EQ Eight → Saturator suave → Limiter.",
      "Plugin gratis: Youlean Loudness Meter para medir LUFS en tiempo real.",
      "NUNCA masterices inmediatamente después de mezclar — descansa los oídos 24h.",
    ],
    abletonParams: {
      targetLUFS: "-6 to -8 club / -14 streaming",
      truePeak: "-0.3 dBTP",
    },
    relatedIds: ["stereo-imaging", "reference-track"],
  },
  {
    id: "reference-track",
    title: "Reference Tracks: Cómo Usarlas Correctamente",
    category: "MIXING",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "La herramienta más infravalorada. Tu oído calibrado con el mercado.",
    steps: [
      "Una reference track es un track profesional que usas como punto de comparación.",
      "Elige referencias del mismo subgénero y BPM similar al tuyo.",
      "Importa la reference en Ableton en un track separado. No toques el volumen.",
      "A/B rápido: alterna entre tu track y la reference cada 10–15 segundos.",
      "Qué comparar: nivel general, cantidad de sub, brillo, amplitud estéreo, compresión.",
      "LUFS matching: iguala el volumen de tu track al de la reference para comparar justo.",
      "No copies — aprende qué hace diferente tu track y ajusta solo lo necesario.",
      "Referencias para techno oscuro: Ben Klock, Surgeon, Phase Fatale en Beatport.",
    ],
    relatedIds: ["mastering-techno", "eq-techno-fundamentals"],
  },

  // ── ARRANGEMENT EXPANDIDO ─────────────────────────────────────────
  {
    id: "breakdown-design",
    title: "Breakdown: Cómo Construir Tensión Real",
    category: "ARRANGEMENT",
    subgenre: "All",
    level: "intermediate",
    time: "20 min",
    description: "El descanso que hace el drop más devastador.",
    steps: [
      "El breakdown es el momento de descanso que hace el drop más impactante.",
      "Duración: 8 a 32 bars según la intensidad del track.",
      "Qué quitar: kick y bass primero. Luego hi-hats. Deja solo atmósferas.",
      "Qué añadir: reverb larga en lo que queda, subida gradual de tensión.",
      "Filter automation: cierra el filtro de elementos durante el breakdown.",
      "Riser: empieza 4–8 bars antes del drop para crear anticipación.",
      "El drop debe ser INMEDIATO después del riser — sin transición suave.",
      "Tip: el silencio de 1/4 de beat antes del drop es la herramienta más poderosa.",
    ],
    relatedIds: ["tension-build", "riser-sweep"],
  },
  {
    id: "automation-mastery",
    title: "Automation: El Secreto de los Tracks Profesionales",
    category: "ARRANGEMENT",
    subgenre: "All",
    level: "intermediate",
    time: "25 min",
    description: "Sin automation, un track suena estático. Con automation, vive.",
    steps: [
      "Los tracks planos sin automation suenan estáticos y amateurs.",
      "Filter automation: la más usada en techno. Cierra y abre el filtro gradualmente.",
      "Volumen automation: fade in y fade out de elementos para que entren naturalmente.",
      "Reverb automation: más reverb en breaks, menos en drops para claridad.",
      "Pan automation: mueve elementos en el stereo field para movimiento.",
      "Pitch automation: modulación de pitch en elementos secundarios para hipnosis.",
      "Ableton: cmd+A en un parámetro para activar automation. Dibuja con ratón.",
      "Tip: menos automation visible = más impacto en los momentos clave.",
    ],
    relatedIds: ["club-structure", "breakdown-design"],
  },

  // ── DJ STYLES adicionales ─────────────────────────────────────────
  {
    id: "phase-fatale-style",
    title: "Phase Fatale Style",
    category: "DJ STYLES",
    subgenre: "Dark Techno",
    level: "advanced",
    bpm: "133–136",
    time: "40 min",
    description: "Oscuro, cinematográfico y deliberado. El sonido de Afterlife.",
    steps: [
      "BPM 133–136 — oscuro y deliberado.",
      "Kicks profundos con mucho sub y poca agresividad superficial.",
      "Atmósferas densas y cinematográficas como elemento principal.",
      "Modulación: todo se mueve lentamente pero constantemente.",
      "Sin melodías obvias — el movimiento tonal viene de filtros y envelopes.",
      "Labels: Afterlife, Methkin — estudia esas releases como referencia.",
      "El espacio y el silencio son tan importantes como los sonidos.",
    ],
    abletonParams: {
      bpm: "133–136",
      atmosphere: "cinematic, dense",
      modulation: "slow, constant",
    },
    isPro: true,
    relatedIds: ["dark-techno-kick", "atmospheric-drone"],
  },
  {
    id: "nico-moreno-style",
    title: "Nico Moreno Style",
    category: "DJ STYLES",
    subgenre: "Hard Techno",
    level: "advanced",
    bpm: "145–150",
    time: "35 min",
    description: "Roto de forma intencional. La distorsión como estética.",
    steps: [
      "BPM 145–150 — rápido y agresivo.",
      "Kicks muy distorsionados, industriales, sin reverb.",
      "Basslines que se fusionan con el kick — casi indistinguibles.",
      "Textura: todo suena 'roto' de forma intencional.",
      "Distorsión extrema como característica estética, no error.",
      "Label R-Label Group define este sound — escucha sus releases.",
      "Menos melodía, más textura y agresión rítmica.",
    ],
    abletonParams: {
      bpm: "145–150",
      distortion: "extreme, intentional",
    },
    isPro: true,
    relatedIds: ["hard-techno-kick", "industrial-kick"],
  },
  {
    id: "stephan-bodzin-style",
    title: "Stephan Bodzin Style",
    category: "DJ STYLES",
    subgenre: "Melodic Techno",
    level: "intermediate",
    bpm: "128–132",
    time: "40 min",
    description: "El melodic techno más sofisticado. Analógico, espacioso, narrativo.",
    steps: [
      "BPM 128–132 — el melodic techno más sofisticado.",
      "Síntesis analógica: Bodzin usa Korg MS-20 y modulares extensamente.",
      "Armonías: acordes mayores y menores en capas, evolución gradual.",
      "Producción: muy limpia y espaciosa — cada elemento tiene su lugar.",
      "Basslines melódicas que cuentan una historia.",
      "Referencia: álbum 'Liebe ist Egal' — producción de referencia absoluta.",
      "En Ableton: Serum para los leads, Analog para warmth, mucho reverb de calidad.",
    ],
    abletonParams: {
      bpm: "128–132",
      synthesis: "analog-style, Serum + Analog",
      reverb: "high quality, spacious",
    },
    isPro: true,
    relatedIds: ["melodic-techno-kick", "deep-house-pad"],
  },

  // ── FUNDAMENTALS ──────────────────────────────────────────────────
  {
    id: "what-is-drum-rack",
    title: "Qué es un Drum Rack y cómo usarlo",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "El instrumento central de Ableton para cualquier producción con batería.",
    steps: [
      "Un Drum Rack es un instrumento virtual de Ableton que agrupa todos tus sonidos de batería en un solo lugar.",
      "Piensa en él como una caja de ritmos digital: cada pad = un sonido diferente.",
      "Cómo abrirlo: crea un MIDI track → arrastra 'Drum Rack' desde Instruments al track.",
      "Cada pad del grid puede contener un sample (kick, snare, hihat, etc.).",
      "Para añadir un sonido: arrastra cualquier archivo de audio desde el browser al pad.",
      "Cada pad tiene su propia cadena de efectos — puedes procesar cada sonido por separado.",
      "Layering: arrastra un segundo sample al mismo pad y elige 'Layer' — ambos suenan juntos.",
      "Choke groups: asigna open y closed hihat al mismo grupo — el closed corta al open automáticamente.",
      "Extract chains: click derecho en un pad → Extract Chains → cada sonido va a su propio track.",
      "Por qué usarlo: organización, control individual de cada elemento, y velocidad de producción.",
    ],
    relatedIds: ["anatomy-of-a-beat", "where-each-sound-goes"],
  },
  {
    id: "anatomy-of-a-beat",
    title: "Anatomía de un Beat: Para qué sirve cada sonido",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "15 min",
    description: "Cada sonido tiene un rol. Entender cuál es cambia todo.",
    steps: [
      "KICK (bombo): el corazón del track. Marca los tiempos fuertes, en techno en todos los beats (4/4). Frecuencias graves 50–100 Hz.",
      "SNARE (caja): responde al kick. En house/techno suele ir en el beat 2 y 4. Frecuencias medias 200–500 Hz. Da el 'crack' y el backbeat.",
      "CLAP: similar al snare pero más agudo y 'seco'. En techno refuerza el snare o va solo. Define el groove junto al kick.",
      "CLOSED HIHAT: las 8vas o 16vas notas entre kicks. Mantiene el tiempo y da energía. Frecuencias altas 8–12 kHz. En techno suelen ser rígidos y constantes.",
      "OPEN HIHAT: el hihat que 'respira'. Da aire al groove. Va en off-beats. Más presencia y sustain que el closed.",
      "RIDE: platillo que reemplaza al hihat en momentos de más energía. Más brillante y sostenido.",
      "SHAKER: textura en alta frecuencia entre los hihats. Da humanidad al groove.",
      "PERCUSIÓN (congas, toms, rimshots): capas extra de groove. En techno dan feeling tribal o industrial.",
      "CRASH: marca momentos importantes — cambios de sección, drops. Úsalo con moderación.",
      "RUIDO/NOISE: en techno industrial el ruido ES un instrumento. Textura y atmósfera.",
    ],
    relatedIds: ["what-is-drum-rack", "where-each-sound-goes", "909-vs-808"],
  },
  {
    id: "where-each-sound-goes",
    title: "Dónde va cada sonido en el bar",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "El mapa del ritmo. Cada posición tiene su lógica.",
    steps: [
      "Un bar de 4/4 tiene 4 beats: 1 — 2 — 3 — 4.",
      "Cada beat se divide en 4 subdivisiones de 16 notas (1/16): 1.1, 1.2, 1.3, 1.4.",
      "KICK: beats 1, 2, 3 y 4 en techno (four-on-the-floor). Siempre en el downbeat.",
      "SNARE/CLAP: beats 2 y 4. Contratipo con el kick.",
      "CLOSED HIHAT: cada 1/8 (entre cada kick) o cada 1/16 para más energía.",
      "OPEN HIHAT: off-beats — entre el 2 y el 3, o entre el 4 y el 1 del siguiente bar.",
      "PERCUSIÓN: rellena los huecos entre kick y hihat. Sin posición fija — experimenta.",
      "Regla de oro: el kick define el ritmo, el hihat define la energía, el snare define el groove.",
      "En Ableton: activa la grid de 1/16 para ver todas las posiciones disponibles.",
      "Tip: empieza con kick + hihat cerrado. Añade lo demás uno a uno escuchando el resultado.",
    ],
    relatedIds: ["anatomy-of-a-beat", "drum-programming-groove", "bpm-and-time-signatures"],
  },
  {
    id: "what-is-a-pad",
    title: "Qué es un Pad y cuándo usarlo",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "8 min",
    description: "Ambiente, profundidad, emoción. Lo que no se ve pero se siente.",
    steps: [
      "Un pad es un sonido de sintetizador con ataque lento, sustain largo y mucha atmósfera.",
      "Para qué sirve: crear ambiente, profundidad emocional, llenar el espacio armónico.",
      "Cuándo usarlo: en breakdowns para crear tensión, como capa continua detrás del groove.",
      "Géneros: en melodic techno y deep house son protagonistas. En dark techno son sutiles.",
      "Cómo crearlo: synth (Serum/Vital) con attack largo (500ms+), filter abierto, mucho reverb.",
      "Posición en el mix: mid-range, nunca compite con kick o bass. Volumen moderado.",
      "Nota: toca acordes con 3–4 notas. Inversiones de acordes suenan más 'flotantes'.",
      "Procesado: reverb larga + delay + chorus suave para que ocupe el espacio estéreo.",
      "Error común: pad demasiado alto en el mix que tapa todo lo demás.",
      "Referencia: escucha los pads de Stephan Bodzin o Bicep para entender el uso correcto.",
    ],
    relatedIds: ["serum-pad", "deep-house-pad", "atmospheric-drone"],
  },
  {
    id: "what-is-a-lead",
    title: "Qué es un Lead Synth",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "8 min",
    description: "La línea que el oyente recuerda. Presente pero no abusada.",
    steps: [
      "El lead es la melodía principal del track — la línea que el oyente recuerda.",
      "Características: ataque rápido, sonido brillante y presente, mono o con poca reverb.",
      "En techno: el lead es esporádico y oscuro, no continuo como en pop.",
      "En melodic techno: el lead cuenta una historia — evoluciona durante el track.",
      "Cómo crearlo: Serum con saw wave, filter en 1 kHz, sin mucho reverb para presencia.",
      "Posición en el mix: mid-high range (500 Hz–3 kHz), por encima del bass y bajo de los hihats.",
      "Cuándo aparece: en el drop principalmente. En breakdowns puede estar solo.",
      "Diferencia con pad: el lead tiene movimiento y melodía. El pad es armónico y estático.",
      "Error común: lead demasiado brillante que 'perfora' la mezcla — usa low pass filter.",
      "Tip: un lead de 4 notas bien procesado es más efectivo que uno de 16 notas.",
    ],
    relatedIds: ["lead-synth-techno", "serum-basics", "what-is-a-pad"],
  },
  {
    id: "what-is-a-bassline",
    title: "Qué es una Bassline y su Rol",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "El low-end que mueve el floor. Su relación con el kick lo es todo.",
    steps: [
      "La bassline lleva el low-end del track junto con el kick — son inseparables.",
      "Para qué sirve: groove, energía, movimiento en las frecuencias bajas.",
      "Frecuencias: principalmente 60–200 Hz. El sub puro está en 30–80 Hz.",
      "Relación con el kick: la bassline no puede 'chocar' con el kick en el mismo tiempo y frecuencia.",
      "Solución: sidechain o programar la bassline para que toque cuando el kick no toca.",
      "En tech house: la bassline ES el hook principal. Groovy, repetitiva, con movimiento.",
      "En dark techno: la bassline es oscura y mínima. Refuerza el kick sin protagonismo.",
      "En acid: la bassline 303 con filter automation es todo el track.",
      "Cómo empezar: una nota repetida con ritmo interesante es mejor que una melodía compleja.",
      "Mono: siempre en mono por debajo de 150 Hz para compatibilidad de sistema de sonido.",
    ],
    relatedIds: ["sub-bass-design", "serum-bassline", "tech-house-bassline"],
  },
  {
    id: "what-are-scratches",
    title: "Qué son los Scratches y Glitches",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "8 min",
    description: "El error como herramienta. Cómo usar el caos de forma controlada.",
    steps: [
      "Scratch: sonido creado por mover un vinilo hacia atrás y adelante en un tocadiscos. En producción: efecto de DJ aplicado a cualquier sample.",
      "En Ableton: usa el clip con Warp activado y mueve la posición de reproducción manualmente.",
      "Plugin: iZotope Stutter Edit 2 o Effectrix para scratches y stutter effects automáticos.",
      "Glitch: error digital deliberado — fragmentation, bit-crushing, buffer stuttering.",
      "Cómo hacer glitch en Ableton: Redux plugin para bit-crushing, Buffer Shuffler M4L device.",
      "Cuándo usar scratches: transiciones, fills, momentos de énfasis — NO de forma continua.",
      "Cuándo usar glitch: en breakdowns para crear tensión, en drops para impacto.",
      "Géneros que más los usan: IDM, glitch hop, algunos momentos en industrial techno.",
      "En techno oscuro: el glitch es sutil — un crackle, un skip, no un festival de errores.",
      "Tip: graba el scratch de un vinilo real y úsalo como sample — más orgánico que los digitales.",
    ],
    relatedIds: ["noise-design", "vocal-processing"],
  },
  {
    id: "what-is-synthesis",
    title: "Síntesis de Sonido: Los 4 Tipos Básicos",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "15 min",
    description: "Cómo se crea el sonido electrónico. La base de todo lo demás.",
    steps: [
      "SÍNTESIS SUBSTRACTIVA: comienzas con un sonido rico (saw, square) y quitas frecuencias con filtros. La más común en synths analógicos. Serum, Vital, Ableton Analog.",
      "SÍNTESIS FM (Frequency Modulation): un oscilador modifica el timbre de otro. Crea sonidos metálicos, percusivos, complejos. Ableton Operator, Yamaha DX7.",
      "SÍNTESIS WAVETABLE: usa tablas de formas de onda que puedes recorrer. Permite transiciones de timbre únicas. Serum, Ableton Wavetable.",
      "SÍNTESIS GRANULAR: trocea el audio en granos diminutos y los reorganiza. Crea texturas imposibles. Ableton Granulator II (gratis), Portal.",
      "Para techno: substractiva (basslines, leads), FM (percusión metálica), wavetable (pads evolutivos), granular (atmósferas).",
      "ADSR: Attack (cuánto tarda en sonar), Decay (cuánto tarda en bajar), Sustain (nivel mientras mantienes), Release (cuánto tarda en apagarse).",
      "ADSR en kick: attack 0ms, decay 200ms, sustain 0, release 100ms.",
      "ADSR en pad: attack 500ms, decay 0, sustain máximo, release 2000ms.",
      "LFO (Low Frequency Oscillator): oscilador muy lento que modula parámetros. Conectado al filtro = movimiento automático.",
      "Tip: aprende síntesis substractiva primero. Todo lo demás viene después.",
    ],
    relatedIds: ["serum-basics", "operator-fm", "vital-synth"],
  },
  {
    id: "ableton-session-vs-arrangement",
    title: "Session View vs Arrangement View en Ableton",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "10 min",
    description: "Las dos vistas que confunden a todos. Cuándo usar cada una.",
    steps: [
      "Ableton tiene DOS vistas — esto confunde a todos los principiantes.",
      "SESSION VIEW (cuadrícula): para improvisar, crear loops, experimentar en tiempo real. Lo que ves son clips que puedes activar en cualquier orden.",
      "ARRANGEMENT VIEW (línea de tiempo): para componer el track final de principio a fin. Como una línea de tiempo de izquierda a derecha.",
      "Flujo de trabajo recomendado: crea tus sonidos e ideas en Session View → cuando tengas el material, grábalo en Arrangement View.",
      "Cómo grabar de Session a Arrangement: activa el botón de grabación y toca los clips en Session — se graban automáticamente en Arrangement.",
      "Tab: cambia entre las dos vistas con la tecla Tab.",
      "Para techno en vivo: muchos DJs usan Session View para mezclar clips en tiempo real.",
      "Para producción: trabaja en Arrangement cuando tengas claro cómo va el track.",
      "MIDI vs Audio tracks: MIDI = datos musicales (notas). Audio = sonido grabado. Los synths van en MIDI, los samples directos en Audio.",
      "Tip: no te bloquees eligiendo vista. Empieza donde te sientas cómodo.",
    ],
    relatedIds: ["what-is-drum-rack", "automation-mastery"],
  },
  {
    id: "frequency-spectrum-basics",
    title: "El Espectro de Frecuencias: Qué va Dónde",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "12 min",
    description: "El mapa del sonido. Sin esto, mezclar es adivinar.",
    steps: [
      "SUB (20–60 Hz): lo que SIENTES más que oyes. Kick, sub bass. Solo el kick y bass deben vivir aquí.",
      "BASS (60–200 Hz): el cuerpo del kick y el body del bass. El 'calor' de un track.",
      "LOW MID (200–500 Hz): zona 'turbia' — aquí se acumula el mud. HPF en casi todos los elementos.",
      "MID (500 Hz–2 kHz): voces, snares, leads. La zona de mayor sensibilidad del oído humano.",
      "HIGH MID (2–8 kHz): presencia, ataque, claridad. Los hihats viven aquí.",
      "AIR (8–20 kHz): brillo, 'aire'. Lo que hace que una mezcla suene abierta.",
      "Regla de techno: cada elemento tiene su 'casa' en el espectro. No deben competir.",
      "Herramienta: Ableton Spectrum (analyzer) — úsalo para ver qué frecuencias tiene cada sonido.",
      "EQ High Pass Filter: tu mejor amigo. Quita lo que no necesita cada elemento.",
      "Tip: si algo suena 'sucio' o 'turbio', busca en 200–400 Hz y corta ahí.",
    ],
    relatedIds: ["eq-techno-fundamentals", "sub-bass-design"],
  },
  {
    id: "bpm-and-time-signatures",
    title: "BPM y Compás: Lo Básico",
    category: "FUNDAMENTALS",
    subgenre: "All",
    level: "beginner",
    time: "8 min",
    description: "La velocidad y la estructura del tiempo. El punto de partida de todo.",
    steps: [
      "BPM (Beats Per Minute): velocidad del track. 120 BPM = 120 kicks por minuto.",
      "Dark Techno: 130–138 BPM. Tech House: 120–128. Hard Techno: 145–160. Deep House: 118–124.",
      "4/4: el compás universal de la música electrónica. 4 beats por bar, 4 es la unidad.",
      "Un bar = 4 beats. 4 bars = una frase. 8 bars = una sección pequeña. 16 bars = una sección.",
      "Los tracks de techno se estructuran en múltiplos de 4: 4, 8, 16, 32, 64 bars.",
      "Grid en Ableton: 1/4 = un beat. 1/8 = entre beats. 1/16 = subdivisión mínima habitual.",
      "Snap: activa el snap al grid para que todo quede perfectamente en tiempo.",
      "Groove/Swing: pequeñas variaciones del timing que hacen el ritmo más humano.",
      "Cómo elegir BPM: empieza con el BPM de tu referencia favorita del género.",
      "Cambiar BPM en Ableton: arriba a la izquierda del interfaz. Afecta todo el proyecto.",
    ],
    relatedIds: ["where-each-sound-goes", "drum-programming-groove"],
  },
];

export function getTechniqueById(id: string): Technique | undefined {
  return techniques.find((t) => t.id === id);
}

export function getTechniquesByCategory(category: Category): Technique[] {
  return techniques.filter((t) => t.category === category);
}

export function getRelatedTechniques(ids: string[]): Technique[] {
  return ids.map((id) => getTechniqueById(id)).filter(Boolean) as Technique[];
}
